### ISSUE TITLE
Calculation failed_ecoinvent_APOS_openlca Alpha version

### ISSUE THREAD

**Issue by R2D2-ad** [GreenDelta/olca-app#149]
Hi!
I run an impact calculation this morning using the Alpha version of openlca, ecoinvent_APOS database and had a failure on the results (see below)
Thank you in advance for the review and reply!

# Error description
# Steps to reproduce

1. Create product system
2. Calculate the impact using RECIPE (Midpoint H)
3. Combined databases (ecoinvent,agribalyse,esu)

# Attached files

* ecoinvent_APOS
* see below

# openLCA error message
Calculation failed
# Installation details
* openLCA version: 2.0.0.alpha3
* operating system: Windows 10
* os architecture: amd64
* os version: 10.0
* native libraries loaded: true
* with sparse matrix support: false
**# Full error stack trace**
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1033)
	at org.openlca.app.wizards.calculation.CalculationWizard.performFinish(CalculationWizard.java:109)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.openlca.app.wizards.calculation.CalculationWizard.open(CalculationWizard.java:63)
	at org.openlca.app.editors.systems.ProductSystemInfoPage.lambda$7(ProductSystemInfoPage.java:118)
	at org.openlca.app.util.Controls$1.widgetSelected(Controls.java:72)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.openlca.app.rcp.RcpApplication.start(RcpApplication.java:16)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
Caused by: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4889)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.widgets.Display.error(Display.java:1262)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:817)
	at org.eclipse.swt.widgets.Display.getActiveShell(Display.java:1480)
	at org.openlca.app.util.UI.shell(UI.java:119)
	at org.openlca.app.wizards.calculation.MemoryError$Dialog.<init>(MemoryError.java:27)
	at org.openlca.app.wizards.calculation.MemoryError.show(MemoryError.java:20)
	at org.openlca.app.wizards.calculation.CalculationWizard.lambda$1(CalculationWizard.java:115)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

Screeshots

``
![Screenshot (6)](https://user-images.githubusercontent.com/32665075/150484411-66fe5e10-991b-413a-aa99-e6fe1430fdf1.png)
`

**Comment by msrocka** [comment]
Many thanks for using the template of the new error reporter! It tries to open the `out of memory error dialog` but this fails because of an invalid thread access. So the reason for the calculation failure is that there is not enough memory (see also https://ask.openlca.org/594/how-to-assign-more-memory-to-openlca). You can also try to download the 'sparse matrix' libraries (there should be a download link on the start page), this should reduce the memory requirements.

**Comment by R2D2-ad** [comment]
Many thanks, the issue is solved!

**Comment by R2D2-ad** [comment]
Hi !
I have to say that I experienced the same issue today. I already increased the memory in openlca.exe to 5GB and my RAM is 32GB. Would it be wise to increase the memory more?

**Comment by msrocka** [comment]
When you download the additional libraries by clicking the link on the start page (or via preferences > configuration), openLCA can use sparse matrix algorithms after a restart. In the calculation dialog select `Lazy/On-demand` as calculation type and it should use much much less memory. This is available in the current [beta version](https://share.greendelta.com/index.php/s/76uAFtMKDIWGoXC).
