### ISSUE TITLE
macOS: “openLCA.app” is damaged and can’t be opened. 

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/olca-app#152]
When you start openLCA on macOS the first time you may see an error message like this:

![image](https://user-images.githubusercontent.com/3520062/154017685-1476ffaf-e274-49e8-b820-802d9d7af072.png)

The reason for this is that openLCA is not a signed application and the security settings of macOS do not allow to run it. To fix this, do the following steps:

* move  the `openLCA_macOS_*.tr.gz` to some other folder than the `Download` folder
* extract this file using the macOS native Archive Utility
* open the Terminal app and navigate to the folder where you extracted openLCA `cd folder/with/openLCA`
* execute the following command: `sudo xattr -r -d com.apple.quarantine openLCA.app`

Another option is to change the security settings globally via `sudo spctl --master-disable` but this does not seem to work on new macOS versions.

Sources:
* http://eclipse.baeyens.it/stable.php?OS=MacOS
* https://github.com/Sloeber/arduino-eclipse-plugin/issues/625

**Comment by SabJacs79** [comment]
Hi,
Im trying to open the file but after executing the following 'sudo xattr -r -d com.apple.quarantine openLCA.app', it asks for a password.  Has anyone encountered that and if so what PW was used?

**Comment by hvs1988** [comment]
> Hi, Im trying to open the file but after executing the following 'sudo xattr -r -d com.apple.quarantine openLCA.app', it asks for a password. Has anyone encountered that and if so what PW was used?

I have the same problem.

**Comment by msrocka** [comment]
`sudo` is an administrator command; you need to enter the password of the current user account that needs to have administrator rights; see e.g. https://support.apple.com/guide/terminal/enter-administrator-commands-apd5b0b6259-a7d4-4435-947d-0dff528912ba/mac

**Comment by SabJacs79** [comment]
thanks @msrocka,
I've tried that but it still does not work.  Its really to bad the product is so complicated to install.  Would anyone have any other alternative ideas of a free LCA software to use?

**Comment by Shreyaskatti97** [comment]
Hello Everyone, I installed it on the MacOs M1 Chip -

Please follow the below steps 
- Open Safari & Download the LCA file (Don't Download using Google Chrome)
- Move/Copy the downloaded file from Download folder to any other folder 
- Open the file using the archive utility
- App will be installed
- From the dock you can open the OpenLCA application

**Comment by Shiva112211** [comment]
Use Safari and then go step by step :
move the openLCA_macOS_*.tr.gz to some other folder than the Download folder
extract this file using the macOS native Archive Utility
open the Terminal app and navigate to the folder where you extracted openLCA cd folder/with/openLCA
execute the following command: sudo xattr -r -d com.apple.quarantine openLCA.app

**Comment by dcecchis** [comment]
> 

I just installed it in a 2021 MacBook Pro M1 Pro, with Monterrey 12.3 following the steps given by @Shiva112211, and I opened it with no problem. I move it into /Applications directory to be available system-wide.

**Comment by Tjob1** [comment]
I downloaded the program in my safari browser, moved the file to another folder and extracted it, but when i use the cd folder/with/openLCA in terminal, it says; no such file or directory: folder/with/openLCA. How do i fix this?

**Comment by dcecchis** [comment]
> I downloaded the program in my safari browser, moved the file to another folder and extracted it, but when i use the cd folder/with/openLCA in terminal, it says; no such file or directory: folder/with/openLCA. How do i fix this?

@Tjob1 in the instructions, "folder/with/openLCA" is a dummy directory name. So, it refers to the location where you moved the program file. For example, in my case, I moved to /Applications, then when I opened the terminal I executed "cd /Applications". Let me know if I clarified your problem and you could fix the problem.

**Comment by Adco-0000** [comment]
I've got quite a few "dev" friends and I will apologize on their behalf for not being so good at explaining these things to mere mortals with little background of troubleshooting/coding/etc. Its not their fault they live in their world and tend to assume that everyone can work out the missing puzzle pieces ;)

Here are slightly clearer steps and combined with others' contributions that will hopefully help.

1. Download the file openLCA_macOS_*.tr.gz (Using Firefox seems to be a better choice)

2. Move the file openLCA_macOS_*.tr.gz to some other folder than the Download folder ("Applications" folder is best)

3. Extract this file using the macOS native Archive Utility (this is a built in tool in Mac OS, not another downloaded app).
  Option A. Usually right click on downloaded file, then "open with", then select "Archive Utility"
  Option B. Search for it using Spotlight search.  
  Option C. Navigate to this folder to find it "/System/Library/CoreServices/Applications", then "File" and "Expand Archive"

4. Open the Terminal app (also built in and searchable with Spotlight) and navigate to the folder where you extracted openLCA (Navigate to folder means type the "cd" command "space" then location of the file). You should have followed step 2 of course, and if you moved the file to the "Applications" folder then you type "cd /Applications", then Enter.

5. Execute the following command: Means type "sudo xattr -r -d com.apple.quarantine openLCA.app" then Enter. It asks for the password of your current user account then Enter (needs to be administrator user. See msrocka's link if you don't understand).
Note: nothing appears on screen as you type your password so avoid mistakes.

6. If you do not get an error message, it will seem like nothing happened after pressing Enter. So now you can try opening the App as usual from the Applications folder! (delete the downloaded compressed file if you wish)

Hope this helps :)

**Comment by lijin0222** [comment]
Note that the password you typed is invisible in the Terminal.
Just type the password and then press the enter key.

**Comment by CrisRich58** [comment]
I just used the method suggested by Shreyaskatti97 on March 3, and it worked perfectly. Just add: move the app from the expansion/extraction folder to the Applications folder after the expansion/extraction. Then it will be shown in the Launchpad and can be started from there.

**Comment by lucabolognini** [comment]
Hi guys,
I tried several time, but nothing worked...it's crazy!
I tried also in windows....again....nothing.
There are no other ways to install openLCA???
I followed all the instructions
Please, help me, otherwise....I'll be crazy!
Thanks!

**Comment by lucabolognini** [comment]
Guys, DON'T DO THAT!!!
After this procedure, my MacBook Pro started to shut down! I finished (I hope) all the procedures to come back my PC to a good shape just now.
The instruction doesn't work and produces troubles for your Mac: avoid it!

**Comment by Shreyaskatti97** [comment]
> 

Hello Everyone, I installed it on the MacOs M1 Chip -

Please follow the below steps

Open Safari & Download the LCA file (Don't Download using Google Chrome)
Move/Copy the downloaded file from Download folder to any other folder
Open the file using the archive utility
App will be installed
From the dock you can open the OpenLCA application

**Comment by hoha2208** [comment]
What the hell. Thank you so so so much @Shreyaskatti97 it really worked with opening from the dock. I spent spent so much time and was so desperate :-D Thank youuu!!!!

**Comment by Shreyaskatti97** [comment]
> Hi guys, I tried several time, but nothing worked...it's crazy! I tried also in windows....again....nothing. There are no other ways to install openLCA??? I followed all the instructions Please, help me, otherwise....I'll be crazy! Thanks!



> Hi guys, I tried several time, but nothing worked...it's crazy! I tried also in windows....again....nothing. There are no other ways to install openLCA??? I followed all the instructions Please, help me, otherwise....I'll be crazy! Thanks!

Hello Everyone, I installed it on the MacOs M1 Chip -

Please follow the below steps

Open Safari & Download the LCA file (Don't Download using Google Chrome)
Move/Copy the downloaded file from Download folder to any other folder
Open the file using the archive utility
App will be installed
From the dock you can open the OpenLCA application

**Comment by chamlinL** [comment]
@Shreyaskatti97 I followed your steps but it always says "eclipse quit unexpectedly." any idea what's going on?

**Comment by Shreyaskatti97** [comment]
> @Shreyaskatti97 I followed your steps but it always says "eclipse quit unexpectedly." any idea what's going on?

No idea about it

**Comment by dswidler1** [comment]
Hi guys
@Adco-0000 thank you so much for your detailed description. It helped me a lot to go step by step all the process. However, I am having the same problem as @hoha2208 . This is what I am getting after trying so many times>
dianaswidler@Dianas-MacBook-Air ~ % cd Applications
dianaswidler@Dianas-MacBook-Air Applications % sudo xattr -r -d com.apple.quarantine openLCA.app
xattr: No such file: openLCA.app
dianaswidler@Dianas-MacBook-Air Applications % sudo xattr -r -d com.apple.quarantine openLCA.app
xattr: No such file: openLCA.app
dianaswidler@Dianas-MacBook-Air Applications % 

I get " no such file" after introducing my password (I am also the admin). I don't understand because I do have the openLCA file extracted in my Applications folder and for whatever reason the terminal doesn't recognize it is there. Can anyone help me before I get completely nuts? Thank you
**“Insanity is doing the same thing over and over and expecting different results.”** Albert Einstein

**Comment by jameneyro** [comment]
I just followed the @Shiva112211 process and it works, thanks!

**Comment by ndayafra23** [comment]
This is what worked for me
1. download the LCA file and move it to another folder
2. extract openLCA
3. open "Terminal", type "cd" space and drag the folder in which you extracted openLCA and release it in the Terminal
4. Execute "sudo xattr -r -d com.apple.quarantine openLCA.app" => process ends here
5. Double click openLCA to start using

**Comment by mgin334** [comment]
Hi Guys, any solution about the "Eclipse Quit Unexpectedly" every time I want to add flows in the openLCA?

**Comment by TJTapajyoti** [comment]
This is what worked for me

    download the LCA file and move it to another folder
    extract openLCA
    open "Terminal", type "cd" space and drag the folder in which you extracted openLCA and release it in the Terminal
    Execute "sudo xattr -r -d com.apple.quarantine openLCA.app" => process ends here
    Double click openLCA to start using


M1 PRO 2021. Monterey

**Comment by helpjulia** [comment]
> hive utility

have you solve the problem? I have exactly the same issue. Mac M1 user here

**Comment by helpjulia** [comment]
> ...nope...! in Mac M1 is quite impossible to solve the problem, I tried all the proposed procedures, but nothing.... I solved using windows OS with parallels...

will the problem persists with M2? I just buy M1 and apparently some software behaved the same way like openLCA. have figured some out, but this one failed.
It has always something to do with "zsh" and now I'm running older version of LCA 10.3. it works though

**Comment by okworx** [comment]
> will the problem persists with M2? I just bought M1 and apparently some software behaved the same way like openLCA. have figured some out, but this one failed. Should I change this M1 to other Mac? It has always something to do with "zsh" and now I'm running older version of LCA 10.3. it works though

This doesn't have anything to do with whether you've got an Intel/M1/M2 CPU. It is that since macOS Catalina, applications need to be notarized by Apple.

**Comment by msrocka** [comment]
@okworx many thanks Oliver! Yes, we plan to register for such a developer ID. I will come back to you when there are questions. Thanks!

**Comment by dcecchis** [comment]
Hi @dswidler1 Could you provide a list of the files in your /Applications directory? Just to make sure in fact you have the file in the correct place.

For example, in my system I got (I remove some of the lines for shake of space)

(base) ***@***.*** /Applications % ls -l
total 0
drwxrwxr-x  3 root         wheel   96 Aug 10 21:42 Adobe Acrobat Reader DC.app
lrwxr-xr-x  1 root         admin   37 Jun 27 11:48 Anaconda-Navigator.app -> /opt/anaconda3/Anaconda-Navigator.app
drwxrwxr-x@ 3 dcecchis     admin   96 Apr 19 15:10 Firefox.app
drwxr-xr-x@ 3 _messagebus  staff   96 Jan  6  2022 FreeFem++.app
drwxr-xr-x@ 3 root         wheel   96 Mar 19 17:02 GarageBand.app
drwxrwxr-x@ 3 dcecchis     admin   96 Aug 15 13:51 Google Chrome.app
drwxr-xr-x  3 dcecchis     staff   96 Aug 10 07:40 Grammarly Desktop.app
drwxr-xr-x@ 3 root         wheel   96 Jun 29 11:16 Numbers.app
drwxr-xr-x@ 4 dcecchis     admin  128 Jan  8  2022 Octave.app
drwxr-xr-x@ 3 root         wheel   96 Aug 11 08:11 iMovie.app
drwxrwxrwx@ 4 dcecchis     staff  128 Feb  9  2022 openLCA.app
drwxr-xr-x  3 dcecchis     wheel   96 Aug 19 10:49 zoom.us.app

You can see the file in the directory.

--
Dany De Cecchis
***@***.***

**Comment by dcecchis** [comment]
Hi Harald,

The message you get is because,

*- in the first try, you try to reach a folder that doesn’t exist “Uni/with/openLCA”
*- In the second try, you reach the folder, but you also move into the openLCA.app folder, then when you try the second command the file openLCA.app is not found.

So, be sure you are in the correct folder. First, move only into de folder “Uni”, I suppose would be
cd /Users/heraldhossfeld/Uni

Then you are there, check if the file is in your current working folder. Type
ls 

and you should see the name of openLCA.app

And now, you can type the next command
sudo xattr -r -d com.apple.quarantine openLCA.app

Once you press return, type your password carefully because you will no see any typing on the screen, and return enter.

I hope this help.

Dany

**Comment by NansD** [comment]
on MacOS Ventura (13.0), when following what's described here, I get another error that tells me to check the logs. Here are the logs : 

<details>
<summary>Click to see logs</summary>

```
!SESSION 2022-11-24 09:21:53.381 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en
Framework arguments:  -keyring /Users/nansdumortier/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -data @noDefault -keyring /Users/nansdumortier/.eclipse_keyring

!ENTRY org.eclipse.osgi 4 0 2022-11-24 09:21:56.541
!MESSAGE An error occurred while automatically activating bundle olca-app (6).
!STACK 0
org.osgi.framework.BundleException: Exception in org.openlca.app.rcp.RcpActivator.start() of bundle olca-app.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nansdumortier/Documents/openLCA/openLCA.app/Contents/Eclipse/olca-native/0.0.1/x64/libquadmath.0.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at org.openlca.nativelib.NativeLib.loadFrom(NativeLib.java:67)
	at org.openlca.app.App.getSolver(App.java:74)
	at org.openlca.app.rcp.RcpActivator.start(RcpActivator.java:72)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 31 more
Root exception:
java.lang.UnsatisfiedLinkError: Can't load library: /Users/nansdumortier/Documents/openLCA/openLCA.app/Contents/Eclipse/olca-native/0.0.1/x64/libquadmath.0.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at org.openlca.nativelib.NativeLib.loadFrom(NativeLib.java:67)
	at org.openlca.app.App.getSolver(App.java:74)
	at org.openlca.app.rcp.RcpActivator.start(RcpActivator.java:72)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY org.eclipse.osgi 4 0 2022-11-24 09:21:56.605
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in olca-app was unable to load class org.openlca.app.rcp.RcpApplication.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:198)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle olca-app (6).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	... 15 more
Caused by: org.osgi.framework.BundleException: Exception in org.openlca.app.rcp.RcpActivator.start() of bundle olca-app.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	... 24 more
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nansdumortier/Documents/openLCA/openLCA.app/Contents/Eclipse/olca-native/0.0.1/x64/libquadmath.0.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at org.openlca.nativelib.NativeLib.loadFrom(NativeLib.java:67)
	at org.openlca.app.App.getSolver(App.java:74)
	at org.openlca.app.rcp.RcpActivator.start(RcpActivator.java:72)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 31 more

```
</details>

**Comment by NansD** [comment]
It seems to work now, thank you for the great work !

**Comment by quazar-blazar** [comment]
@NansD - what did you end up doing to get it to work? I seem to be in the same boat as you with M2 running the latest version of MacOS. I still can't get it to work and when I get to the part where I'm enter the sudo command I get the following error: 

stevens-air openLCA.app % sudo xattr -r -d com.apple.quarantine openLCA.app
xattr: No such file: openLCA.app

**Comment by NansD** [comment]
> @NansD - what did you end up doing to get it to work? I seem to be in the same boat as you with M2 running the latest version of MacOS. I still can't get it to work and when I get to the part where I'm enter the sudo command I get the following error:
> 
> stevens-air openLCA.app % sudo xattr -r -d com.apple.quarantine openLCA.app xattr: No such file: openLCA.app



I used [this approach](https://github.com/GreenDelta/olca-app/issues/152#issuecomment-1232338540). 
> This is what worked for me
> 
> 1. download the LCA file and move it to another folder
> 2. extract openLCA
> 3. open "Terminal", type "cd" space and drag the folder in which you extracted openLCA and release it in the Terminal
> 4. Execute "sudo xattr -r -d com.apple.quarantine openLCA.app" => process ends here
> 5. Double click openLCA to start using
In your example it looks like you missed step 3, where you have to place yourself in the right directory before running step 4

**Comment by studds** [comment]
@msrocka are there any plans to sign this? It's pretty bad practice to tell people to run a random app off the internet with `sudo`.

**Comment by quazar-blazar** [comment]
> > @NansD - what did you end up doing to get it to work? I seem to be in the same boat as you with M2 running the latest version of MacOS. I still can't get it to work and when I get to the part where I'm enter the sudo command I get the following error:
> > stevens-air openLCA.app % sudo xattr -r -d com.apple.quarantine openLCA.app xattr: No such file: openLCA.app
> 
> I used [this approach](https://github.com/GreenDelta/olca-app/issues/152#issuecomment-1232338540).
> 
> > This is what worked for me
> > 
> > 1. download the LCA file and move it to another folder
> > 2. extract openLCA
> > 3. open "Terminal", type "cd" space and drag the folder in which you extracted openLCA and release it in the Terminal
> > 4. Execute "sudo xattr -r -d com.apple.quarantine openLCA.app" => process ends here
> > 5. Double click openLCA to start using
> 
> In your example it looks like you missed step 3, where you have to place yourself in the right directory before running step 4

I actually did this exactly but it still didn't work. I ended up just using my other machine which is running windows. Super sad it had to come to this.

**Comment by HeKatzi** [comment]
> > > @NansD - what did you end up doing to get it to work? I seem to be in the same boat as you with M2 running the latest version of MacOS. I still can't get it to work and when I get to the part where I'm enter the sudo command I get the following error:
> > > stevens-air openLCA.app % sudo xattr -r -d com.apple.quarantine openLCA.app xattr: No such file: openLCA.app
> > 
> > 
> > I used [this approach](https://github.com/GreenDelta/olca-app/issues/152#issuecomment-1232338540).
> > > This is what worked for me
> > > 
> > > 1. download the LCA file and move it to another folder
> > > 2. extract openLCA
> > > 3. open "Terminal", type "cd" space and drag the folder in which you extracted openLCA and release it in the Terminal
> > > 4. Execute "sudo xattr -r -d com.apple.quarantine openLCA.app" => process ends here
> > > 5. Double click openLCA to start using
> > 
> > 
> > In your example it looks like you missed step 3, where you have to place yourself in the right directory before running step 4
> 
> I actually did this exactly but it still didn't work. I ended up just using my other machine which is running windows. Super sad it had to come to this.

I did this and it didn't work at first, eventually I realised I was in the wrong directory (Users/me/Applications) I navigated out of it typing  cd..  (enter) several times in the terminal and then navigated to my applications folder where I put the file before using  cd Applications/  (enter) then I contiunued with step 4 and it worked. (you can check what the content of your current path in the terminal using  ls  and return your current path using pwd).
