### ISSUE TITLE
Plugin manager: uninstallation of a plugin throws error

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/olca-app#19]
something is going wrong with the UI threads ...
```
Caused by: java.lang.IllegalStateException: Not on FX application thread; currentThread = ModalContext
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.web.WebEngine.checkThread(WebEngine.java:1216)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:980)
	at org.openlca.app.rcp.plugins.PluginManager.refresh(Unknown Source)
	at org.openlca.app.rcp.plugins.PluginManager.access$1(Unknown Source)
	at org.openlca.app.rcp.plugins.PluginManager$JsHandler.lambda$2(Unknown Source)
	at org.openlca.app.App.lambda$0(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by msrocka** [comment]
We disabled the plugin manager in openLCA 1.7.2 as we do not longer use it
