### ISSUE TITLE
Export ef_secondarydata_202202 database, save as JSON-LD format report error

### ISSUE THREAD

**Issue by kelilive** [GreenDelta/olca-app#350]
The database file is too big, it's 3GB, it's a free public database on the official website. Please test it yourself, I don't know if it has anything to do with the file being too big. So far, I've only encountered this database error.

# Attached files

![image](https://github.com/GreenDelta/olca-app/assets/142982913/b52bdf58-2e34-4774-969b-28c918ed8911)

# openLCA error message

Failed to export data sets

# Installation details

* openLCA version: 2.0.1
* operating system: Windows 10
* os architecture: amd64
* os version: 10.0
* native libraries loaded: true
* with sparse matrix support: false

# Full error stack trace

```
java.lang.reflect.InvocationTargetException

	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:395)

	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1034)

	at org.openlca.app.wizards.io.JsonExportWizard.performFinish(JsonExportWizard.java:57)

	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:833)

	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:473)

	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)

	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)

	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)

	at org.eclipse.jface.window.Window.open(Window.java:799)

	at org.eclipse.ui.internal.handlers.WizardHandler$Export.executeHandler(WizardHandler.java:104)

	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:283)

	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)

	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)

	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)

	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)

	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)

	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)

	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)

	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)

	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)

	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)

	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:366)

	at org.openlca.app.navigation.actions.ExportAction.run(ExportAction.java:53)

	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)

	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)

	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)

	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)

	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)

	at org.openlca.app.rcp.RcpApplication.start(RcpApplication.java:16)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

Caused by: java.lang.OutOfMemoryError: Java heap space

	at java.base/java.util.Arrays.copyOf(Unknown Source)

	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)

	at java.base/java.lang.AbstractStringBuilder.append(Unknown Source)

	at java.base/java.lang.StringBuffer.append(Unknown Source)

	at java.base/java.io.StringWriter.write(Unknown Source)

	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:642)

	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402)

	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:417)

	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:832)

	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)

	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)

	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:838)

	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:846)

	at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:725)

	at com.google.gson.internal.Streams.write(Streams.java:73)

	at com.google.gson.Gson.toJson(Gson.java:930)

	at com.google.gson.Gson.toJson(Gson.java:863)

	at com.google.gson.Gson.toJson(Gson.java:848)

	at org.openlca.jsonld.JsonStoreWriter.put(JsonStoreWriter.java:26)

	at org.openlca.jsonld.JsonStoreWriter.put(JsonStoreWriter.java:20)

	at org.openlca.jsonld.output.JsonExport.write(JsonExport.java:194)

	at org.openlca.app.wizards.io.JsonExportWizard$Export.doExport(JsonExportWizard.java:107)

	at org.openlca.app.wizards.io.JsonExportWizard$Export.doExport(JsonExportWizard.java:100)

	at org.openlca.app.wizards.io.JsonExportWizard$Export.run(JsonExportWizard.java:83)

	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)


```

**Comment by cestiil** [comment]
I got the same error with exporting user-created processes from ecoinvent v3.8. 
Is anyone dealing with this issue?

**Comment by kelilive** [comment]
Hey, there isn't any better way to do this, open source products are just that, very hopeless.

**Comment by francoislerall** [comment]
You can increase memory usage:
![image](https://github.com/GreenDelta/olca-app/assets/43290668/bb045d71-fceb-463c-bfe1-52526e318a32)

**Comment by kelilive** [comment]
Hi, @francoislerall

Of course, I haven't reproduced it yet, maybe I forgot some steps or something. Thank you for your explanation and answer, which let me know more details and try methods.

Maybe we should give users more friendly prompts, not everyone is a programmer. I am a programmer, and I can probably understand some of the exception information. Exceptions should not usually be thrown to users, and they cannot help them solve problems through exceptions. So, I hope to be improved.
