### ISSUE TITLE
Textbox input length check

### ISSUE THREAD

**Issue by kelilive** [GreenDelta/olca-app#351]
# Attached files

![image](https://github.com/GreenDelta/olca-app/assets/142982913/507dbb7f-69a2-4f48-9ae2-7e28d124fd7f)

# openLCA error message

failed to update FlowProperty

# Installation details

* openLCA version: 2.0.1
* operating system: Windows 10
* os architecture: amd64
* os version: 10.0
* native libraries loaded: true
* with sparse matrix support: false

# Full error stack trace

```
org.openlca.core.database.DatabaseException: Error while updating FlowProperty

	at org.openlca.core.database.DatabaseException.logAndThrow(DatabaseException.java:19)

	at org.openlca.core.database.BaseDao.update(BaseDao.java:113)

	at org.openlca.app.editors.ModelEditor.doSave(ModelEditor.java:153)

	at org.eclipse.ui.internal.SaveableHelper.lambda$0(SaveableHelper.java:156)

	at org.eclipse.ui.internal.SaveableHelper.lambda$3(SaveableHelper.java:271)

	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:434)

	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)

	at org.eclipse.ui.internal.WorkbenchWindow.lambda$7(WorkbenchWindow.java:2346)

	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)

	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2344)

	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:278)

	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:260)

	at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:160)

	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3802)

	at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3815)

	at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:82)

	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)

	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)

	at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)

	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)

	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)

	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)

	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)

	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)

	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)

	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)

	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)

	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:580)

	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:647)

	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:439)

	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1286)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)

	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)

	at org.eclipse.swt.widgets.Text.sendKeyEvent(Text.java:1821)

	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)

	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1594)

	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4865)

	at org.eclipse.swt.widgets.Text.WM_CHAR(Text.java:2705)

	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4743)

	at org.eclipse.swt.widgets.Text.windowProc(Text.java:2687)

	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5022)

	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3640)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)

	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)

	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)

	at org.openlca.app.rcp.RcpApplication.start(RcpApplication.java:16)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

Caused by: jakarta.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 3.0.3.v202208191135): org.eclipse.persistence.exceptions.DatabaseException

Internal Exception: java.sql.SQLDataException: A truncation error was encountered trying to shrink CLOB '111111111111111111111111111111111111111111111111111111111111&' to length 65536.

Error Code: 20000

Call: UPDATE tbl_flow_properties SET description = ?, last_change = ?, version = ? WHERE (id = ?)

	bind => [4 parameters bound]

	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:163)

	at org.openlca.core.database.BaseDao.update(BaseDao.java:110)

	... 69 more

Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 3.0.3.v202208191135): org.eclipse.persistence.exceptions.DatabaseException

Internal Exception: java.sql.SQLDataException: A truncation error was encountered trying to shrink CLOB '111111111111111111111111111111111111111111111111111111111111&' to length 65536.

Error Code: 20000

Call: UPDATE tbl_flow_properties SET description = ?, last_change = ?, version = ? WHERE (id = ?)

	bind => [4 parameters bound]

	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:334)

	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:917)

	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:979)

	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:640)

	at org.eclipse.persistence.internal.databaseaccess.ParameterizedSQLBatchWritingMechanism.executeBatch(ParameterizedSQLBatchWritingMechanism.java:155)

	at org.eclipse.persistence.internal.databaseaccess.ParameterizedSQLBatchWritingMechanism.executeBatchedStatements(ParameterizedSQLBatchWritingMechanism.java:140)

	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.writesCompleted(DatabaseAccessor.java:1894)

	at org.eclipse.persistence.internal.sessions.AbstractSession.writesCompleted(AbstractSession.java:4377)

	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.writesCompleted(UnitOfWorkImpl.java:5779)

	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.acquireWriteLocks(UnitOfWorkImpl.java:1713)

	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitTransactionAfterWriteChanges(UnitOfWorkImpl.java:1681)

	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:295)

	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1234)

	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:138)

	... 70 more

Caused by: java.sql.SQLDataException: A truncation error was encountered trying to shrink CLOB '111111111111111111111111111111111111111111111111111111111111&' to length 65536.

	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:84)

	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:230)

	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:431)

	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:360)

	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2400)

	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(ConnectionChild.java:86)

	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1436)

	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(EmbedPreparedStatement.java:1709)

	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(EmbedPreparedStatement.java:320)

	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(EmbedPreparedStatement.java:309)

	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:907)

	... 82 more

Caused by: ERROR 22001: A truncation error was encountered trying to shrink CLOB '111111111111111111111111111111111111111111111111111111111111&' to length 65536.

	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)

	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)

	at org.apache.derby.iapi.types.SQLChar.hasNonBlankChars(SQLChar.java:1846)

	at org.apache.derby.iapi.types.SQLVarchar.normalize(SQLVarchar.java:181)

	at org.apache.derby.iapi.types.SQLVarchar.normalize(SQLVarchar.java:158)

	at org.apache.derby.iapi.types.SQLClob.normalize(SQLClob.java:529)

	at org.apache.derby.iapi.types.DataTypeDescriptor.normalize(DataTypeDescriptor.java:656)

	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(NormalizeResultSet.java:332)

	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(NormalizeResultSet.java:376)

	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(NormalizeResultSet.java:191)

	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(DMLWriteResultSet.java:148)

	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(UpdateResultSet.java:670)

	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(UpdateResultSet.java:479)

	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(UpdateResultSet.java:272)

	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(GenericPreparedStatement.java:470)

	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:349)

	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1344)

	... 86 more


```

**Comment by kelilive** [comment]
There are many similar problems, such as multiple windows can cause the operation to fail, you should analyze why multiple windows can cause this problem and how to deal with it.

**Comment by francoislerall** [comment]
Hello,
I am guessing that you have exceeded the number of characters in the _Description_ of a flow property. The limit is **65536**.
Regards,
François
