### ISSUE TITLE
Failed to run Import database

### ISSUE THREAD

**Issue by DavidCETENMA** [GreenDelta/olca-app#361]
Good morning. I hope all of you are fine.

Following, I am going to describe the issue that I have using OpenLCA + PSILCA database (licence paid)

# Error description

I tried to import PSILCA database but openLCA threw an error.

# Steps to reproduce

1. OpenLCA
2. Clicking on "File"
3. Import
4. Selecting "File" and choosing the file named "psilca_starter_work_hours_cutoff_1_0e_5_20230324.zolca" 

# Attached files
* screen shots 
* ...

# openLCA error message

Failed to run Import database

# Installation details

* openLCA version: 2.0.3
* operating system: Windows 10
* os architecture: amd64
* os version: 10.0
* native libraries loaded: false
* with sparse matrix support: false

# Full error stack trace

```
org.zeroturnaround.zip.ZipException: Failed to process zip entry 'log/log80258.dat' with action org.zeroturnaround.zip.ZipUtil$Unpacker@717981d6

	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:511)

	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:472)

	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:996)

	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:939)

	at org.openlca.app.navigation.actions.db.DbRestoreAction.lambda$1(DbRestoreAction.java:89)

	at org.openlca.app.WrappedJob.run(WrappedJob.java:30)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: java.io.IOException: There is not enough space on the disk

	at java.base/java.io.FileOutputStream.writeBytes(Native Method)

	at java.base/java.io.FileOutputStream.write(Unknown Source)

	at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)

	at java.base/java.io.BufferedOutputStream.write(Unknown Source)

	at org.zeroturnaround.zip.commons.IOUtils.copyLarge(IOUtils.java:323)

	at org.zeroturnaround.zip.commons.IOUtils.copyLarge(IOUtils.java:299)

	at org.zeroturnaround.zip.commons.IOUtils.copy(IOUtils.java:274)

	at org.zeroturnaround.zip.commons.FileUtils.copy(FileUtils.java:56)

	at org.zeroturnaround.zip.ZipUtil$Unpacker.process(ZipUtil.java:1179)

	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:508)

	... 6 more


```

**Comment by msrocka** [comment]
> There is not enough space on the disk

Seems that your disk is full?

**Comment by francoislerall** [comment]
I am closing this issue has there is no feedback from the user.
