### ISSUE TITLE
error create/restore database in macOs

### ISSUE THREAD

**Issue by rosanagalindo** [GreenDelta/olca-app#374]
Hello, 
I'm trying to install backup some databases from my old windows to a macOS (Sonoma 14.2.1, apparently the openLca was installed but it can't create/ restore any database, follow below the error 

# Error description

I tried to ??? but openLCA threw an error.

# Steps to reproduce

1. ?
2. ?
3. ?

# Attached files

* example database ?
* screen shots ?
* ...

# openLCA error message

failed to create database

# Installation details

* openLCA version: 2.0.4
* native libraries loaded: false
* with sparse matrix support: false

# Full error stack trace

```
java.lang.RuntimeException: failed to extract database template FLOWS to /Users/xxx/openLCA-data-1.4/databases/1
	at org.openlca.app.db.DbTemplate.extract(DbTemplate.java:34)
	at org.openlca.app.db.DatabaseWizard$Runner.createIt(DatabaseWizard.java:118)
	at org.openlca.app.db.DatabaseWizard$Runner.run(DatabaseWizard.java:90)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.nio.file.AccessDeniedException: /Users/xxx/openLCA-data-1.4/databases/1
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectories(Unknown Source)
	at org.openlca.app.db.DbTemplate.extract(DbTemplate.java:30)
	... 3 more

```

Many thanks

**Comment by francoislerall** [comment]
Hello,
From the log file I can see that openLCA could not access the DB (`AccessDeniedException: /Users/xxx/openLCA-data-1.4/databases/1`). Could it be that this folder has restricted access? You could check the permission for openLCA or install the latest version.
