### ISSUE TITLE
Importing ReCiPe from Federal LCA Commons

### ISSUE THREAD

**Issue by Gonzalo-RG** [GreenDelta/olca-app#383]
# Error description

I tried to Import the ReCiPe repository available in the Federal LCA Commons webpage (https://www.lcacommons.gov/lca-collaboration/Federal_LCA_Commons/ReCiPe/datasets) but openLCA threw an error.
Is there any way I can fix this?
Thanks!
Gonzalo

# openLCA error message

JSON import failed

# Installation details

* openLCA version: 2.1.0
* operating system: Windows 10
* os architecture: amd64
* os version: 10.0
* native libraries loaded: false
* with sparse matrix support: false

# Full error stack trace

```
java.lang.reflect.InvocationTargetException

	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:395)

	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1034)

	at org.openlca.app.wizards.io.JsonImportWizard.lambda$1(JsonImportWizard.java:91)

	at org.openlca.app.wizards.io.LibraryResolver.resolve(LibraryResolver.java:36)

	at org.openlca.app.wizards.io.JsonImportWizard.doRun(JsonImportWizard.java:87)

	at org.openlca.app.wizards.io.JsonImportWizard.performFinish(JsonImportWizard.java:71)

	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:833)

	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:473)

	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)

	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)

	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)

	at org.eclipse.jface.window.Window.open(Window.java:799)

	at org.openlca.app.wizards.io.Wizards.forImport(Wizards.java:44)

	at org.openlca.app.wizards.io.JsonImportWizard.of(JsonImportWizard.java:39)

	at org.openlca.app.tools.FileImport.handleFormat(FileImport.java:106)

	at org.openlca.app.tools.FileImport.run(FileImport.java:66)

	at org.openlca.app.navigation.actions.NavigationMenu.lambda$2(NavigationMenu.java:179)

	at org.openlca.app.util.Actions$1.run(Actions.java:34)

	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)

	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)

	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)

	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)

	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)

	at org.openlca.app.rcp.RcpApplication.start(RcpApplication.java:13)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

Caused by: java.lang.OutOfMemoryError: Java heap space


```

**Comment by francoislerall** [comment]
Hello,
I have tried to download the DB. Unfortunately, the request was timed out. The reason might be that I am located in Europe and servers are across the Atlantic.
Do you have a way to share the DB with me?
Regards,
François

**Comment by Gonzalo-RG** [comment]
Hello Francois,
I am afraid I lost track of this conversation. I do not know how I was able to fix the problem, but I eventually managed to import the ReCiPe repository. However, I seem to have the same problem with the Impact World one, which I have attached to this message.
Thanks,
Gonzalo 
[ImpactWorld+ - Midpoint_json_v1.0.0.zip](https://github.com/GreenDelta/olca-app/files/14746002/ImpactWorld%2B.-.Midpoint_json_v1.0.0.zip)
[ImpactWorld+ - Endpoint_json_v1.0.0.zip](https://github.com/GreenDelta/olca-app/files/14746014/ImpactWorld%2B.-.Endpoint_json_v1.0.0.zip)

**Comment by francoislerall** [comment]
Hello Gonzalo,
I just tried it now with the latest openLCA release (2.1.1). I did not have any issue. Which version are you using?

**Comment by Gonzalo-RG** [comment]
Hi Francois,

I am using the same version, and I have just tried again, and I get the same message:

* ...

# openLCA error message

JSON import failed

# Installation details

* openLCA version: 2.1.1
* operating system: Windows 10
* os architecture: amd64
* os version: 10.0
* native libraries loaded: false
* with sparse matrix support: false

# Full error stack trace

```
java.lang.reflect.InvocationTargetException

	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:395)

	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1034)

	at org.openlca.app.wizards.io.JsonImportWizard.lambda$1(JsonImportWizard.java:91)

	at org.openlca.app.wizards.io.LibraryResolver.resolve(LibraryResolver.java:36)

	at org.openlca.app.wizards.io.JsonImportWizard.doRun(JsonImportWizard.java:87)

	at org.openlca.app.wizards.io.JsonImportWizard.performFinish(JsonImportWizard.java:71)

	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:833)

	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:473)

	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)

	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)

	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)

	at org.eclipse.jface.window.Window.open(Window.java:799)

	at org.openlca.app.wizards.io.Wizards.forImport(Wizards.java:44)

	at org.openlca.app.wizards.io.JsonImportWizard.of(JsonImportWizard.java:39)

	at org.openlca.app.tools.FileImport.handleFormat(FileImport.java:106)

	at org.openlca.app.tools.FileImport.run(FileImport.java:66)

	at org.openlca.app.navigation.actions.NavigationMenu.lambda$2(NavigationMenu.java:181)

	at org.openlca.app.util.Actions$1.run(Actions.java:34)

	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)

	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)

	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)

	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)

	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)

	at org.openlca.app.rcp.RcpApplication.start(RcpApplication.java:13)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

Caused by: java.lang.OutOfMemoryError: Java heap space


```

**Comment by francoislerall** [comment]
OK, let's detail a bit more what we are doing.
On my side I did the following:
 - create a new DB with Complete reference data,
 - File -> Import -> File 
 - select [ImpactWorld+ - Midpoint_json_v1.0.0.zip](https://github.com/GreenDelta/olca-app/files/14746002/ImpactWorld%2B.-.Midpoint_json_v1.0.0.zip)
 - import was succesfull, I could find the impact assessment method and impact categories.

On your side:
1. Can you describe your steps?
2. Are you importing these files into an existing DB? 
3. Which one?
4. What size?

Regards,
François

**Comment by bl-young** [comment]
@Gonzalo-RG - the ReCipE on the commons is a bit outdated and we have had issues with it due to its sheer size. While we get things updated, I would recommend using the [no flows version](https://www.lcacommons.gov/lcia-methods-without-flows) which is a much smaller JSON object and easier to import into a database. However see the instructions there, it will only add characterization factors for flows that already exist in your database.

**Comment by Gonzalo-RG** [comment]
Thank you Francois, and thank you Ben. The no flows version works.

**Comment by francoislerall** [comment]
Nice, I am happy to hear it!
