### ISSUE TITLE
 I tried to import Excel file(s) but open lca Failed to openLCA threw an error.

### ISSUE THREAD

**Issue by amdfalcon** [GreenDelta/olca-app#398]
# Installation details

* openLCA version: 2.2.0
* operating system: Windows 11
* os architecture: amd64
* os version: 10.0
* native libraries loaded: false
* with sparse matrix support: false
*
![image](https://github.com/GreenDelta/olca-app/assets/166021134/6ebd5d61-2e33-469d-9ab5-0c020ce2eb12)
# Full error stack trace

```
java.lang.reflect.InvocationTargetException

	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:395)

	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1034)

	at org.openlca.app.wizards.io.ExcelImportWizard.performFinish(ExcelImportWizard.java:71)

	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:833)

	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:473)

	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)

	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)

	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)

	at org.eclipse.jface.window.Window.open(Window.java:799)

	at org.openlca.app.wizards.io.Wizards.forImport(Wizards.java:44)

	at org.openlca.app.wizards.io.ExcelImportWizard.of(ExcelImportWizard.java:42)

	at org.openlca.app.tools.FileImport.handleFormat(FileImport.java:98)

	at org.openlca.app.tools.FileImport.run(FileImport.java:67)

	at org.openlca.app.navigation.actions.NavigationMenu.lambda$2(NavigationMenu.java:190)

	at org.openlca.app.util.Actions$1.run(Actions.java:34)

	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)

	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)

	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)

	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)

	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)

	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)

	at org.openlca.app.rcp.RcpApplication.start(RcpApplication.java:13)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

Caused by: java.lang.RuntimeException: failed to read process from file: C:\Users\Admin\Downloads\21-march-CSD- Sugarcane to ethanol Rev 2 (1).xlsx

	at org.openlca.io.xls.process.XlsProcessReader.sync(XlsProcessReader.java:112)

	at org.openlca.app.wizards.io.ExcelImportWizard.lambda$1(ExcelImportWizard.java:77)

	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)


```

**Comment by francoislerall** [comment]
Hello,
Answering quite late, did you find a solution to your issue?
