### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/ui/progress/UIJob

### ISSUE THREAD

**Issue by Gaetan-Collin** [GreenDelta/olca-app#84]
Hello,

When compiling the solution, I got the following error. Can you help me please!

mai 10, 2019 12:35:34 PM org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/eclipse/ui/progress/UIJob] with root cause
java.lang.ClassNotFoundException: org.eclipse.ui.progress.UIJob
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.defineClass1(Native Method)
        ....

Thanks in advance.

Best regards.

**Comment by msrocka** [comment]
not sure what you tried but your stack trace says that you are running this in a Tomcat server (?) ....

This is a desktop application running on the Eclipse RCP platform. When you follow the steps in the README file it should be possible to compile and run it.
